[package]
name = "ragnarok-script-interpreter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#antlr-rust = "0.2.2"
antlr-rust = { git = "https://github.com/nmeylan/antlr4rust", rev = "9d5ad2d780e7c6ccdb0703885348ece4bab06130"}

#[patch."https://github.com/nmeylan/antlr4rust"]
#antlr-rust = {path = "/home/nmeylan/dev/perso/antlr4rust"}